### ISSUE TITLE
Avoid skipping heading levels

### ISSUE THREAD

**Issue by jim-rosales** [Craft4Coffee/colmaracademy#2]
As per the [documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) for the header element, it is best to avoid skipping heading levels. In this case, you skipped the `<h2>` and went from `<h1>` to `<h3>`. It is best practice to always start from `<h1>`, next use` <h2>` and so on. This is because of how the header elements are used by screen readers when visually impaired users visit a site. 

In this case, if you used an `<h3>` instead of an `<h2>` for its smaller size it is best to change the size of the text via some CSS. 

https://github.com/Craft4Coffee/colmaracademy/blob/f85b56a0535355f072eb964d81b1b7d0a4f04751/index.html#L56-L58

**Comment by Craft4Coffee** [comment]
Makes sense. Thank you.
